version: '2'
services:
  ide:
    image: u1ih/ubuntu-novnc
#    image: u1ih/ubuntu-novnc
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: u1ih/ubuntu-novnc
    environment:
      # Adjust to your screen size
      - vncpassword=hello123
    ports:
      - "8080:808"
    networks:
      - x11
networks:
  x11:
