version: '2'
services:
  ide:
    image: ubuntu:20.04 as ubuntu-base
#    image: ubuntu-base as ubuntu-utilities
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - SCREEN_WIDTH=1280 
      - SCREEN_HEIGHT=720 
      - SCREEN_DEPTH=24 
      - SCREEN_DPI=96 
      - DISPLAY=:99 
      - DISPLAY_NUM=99 
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
