version: '2'
services:
  ide:
    image: ubuntu-base as ubuntu-utilities
#    image: ubuntu-base as ubuntu-utilities
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=3840
      - DISPLAY_HEIGHT=2160
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
