version: '2'
services:
  ide:
    image: fredblgr/ubuntu-novnc:20.04
#    image: fredblgr/ubuntu-novnc:20.04
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - RESOLUTION=1920x1080
      - USER=doro
      - PASSWORD=password
    ports:
      - "6080:80"
    networks:
      - x11
networks:
  x11:
